services:
  fastapi:
    build: ./app
    container_name: cars_seven_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - cars_seven_net

  postgres:
    image: postgres:15
    container_name: cars_seven_postgres
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - cars_seven_pgdata:/var/lib/postgresql/data
    networks:
      - cars_seven_net

networks:
  cars_seven_net:
    driver: bridge

volumes:
  cars_seven_pgdata:
